apiVersion: v2
appVersion: "1.0"
description: A helm chart for installing forge
name: forge
sources:
- https://github.com/michaeljguarino/forge
maintainers:
- name: michaeljguarino
  email: mguarino46@gmail.com
version: 0.4.4
dependencies:
- name: postgresql
  version: 8.6.4
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: rabbitmq
  version: 7.6.6
  repository: https://charts.bitnami.com/bitnami