{{- if .Values.ingress.enabled -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: forge
  labels:
{{ include "forge.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.dns }}
    - {{ .Values.ingress.dkr_dns }}
    secretName: forge-tls
  rules:
  - host: {{ .Values.ingress.dns }}
    http:
      paths:
      - path: /cm/.*
        backend:
          serviceName: forge-api
          servicePort: http
      - path: /gql
        backend:
          serviceName: forge-api
          servicePort: http
      - path: /auth/.*
        backend:
          serviceName: forge-api
          servicePort: http
      - path: /api/.*
        backend:
          serviceName: forge-api
          servicePort: http
      - backend:
          serviceName: forge-www
          servicePort: http
  - host: {{ .Values.ingress.dkr_dns }}
    http:
      paths:
      - backend:
          serviceName: forge-registry
          servicePort: http
{{- end }}
