apiVersion: v1
kind: Secret
metadata:
  name: chartmart-env
  labels:
{{ include "chartmart.labels" . | indent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwt | b64enc | quote }}
  SECRET_KEY_BASE: {{ randAlphaNum 10 | b64enc | quote }}
  ERLANG_COOKIE: {{ .Values.secrets.erlang | b64enc | quote }}
