apiVersion: v2
name: plural
description: A helm chart for installing plural
appVersion: "1.0"
version: 0.8.23
dependencies:
- name: hydra
  repository: https://k8s.ory.sh/helm/charts
  version: 0.16.0
maintainers:
- email: mjg@plural.sh
  name: michaeljguarino
sources:
- https://github.com/pluralsh/plural
